// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: plugin.proto

package orcaiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrcaiPlugin_GetInfo_FullMethodName      = "/orcai.v1.OrcaiPlugin/GetInfo"
	OrcaiPlugin_Start_FullMethodName        = "/orcai.v1.OrcaiPlugin/Start"
	OrcaiPlugin_Stop_FullMethodName         = "/orcai.v1.OrcaiPlugin/Stop"
	OrcaiPlugin_GetStatus_FullMethodName    = "/orcai.v1.OrcaiPlugin/GetStatus"
	OrcaiPlugin_Execute_FullMethodName      = "/orcai.v1.OrcaiPlugin/Execute"
	OrcaiPlugin_Capabilities_FullMethodName = "/orcai.v1.OrcaiPlugin/Capabilities"
)

// OrcaiPluginClient is the client API for OrcaiPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrcaiPluginClient interface {
	GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteResponse], error)
	Capabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapabilityList, error)
}

type orcaiPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewOrcaiPluginClient(cc grpc.ClientConnInterface) OrcaiPluginClient {
	return &orcaiPluginClient{cc}
}

func (c *orcaiPluginClient) GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, OrcaiPlugin_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orcaiPluginClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, OrcaiPlugin_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orcaiPluginClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, OrcaiPlugin_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orcaiPluginClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, OrcaiPlugin_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orcaiPluginClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrcaiPlugin_ServiceDesc.Streams[0], OrcaiPlugin_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecuteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrcaiPlugin_ExecuteClient = grpc.ServerStreamingClient[ExecuteResponse]

func (c *orcaiPluginClient) Capabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapabilityList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilityList)
	err := c.cc.Invoke(ctx, OrcaiPlugin_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrcaiPluginServer is the server API for OrcaiPlugin service.
// All implementations must embed UnimplementedOrcaiPluginServer
// for forward compatibility.
type OrcaiPluginServer interface {
	GetInfo(context.Context, *Empty) (*PluginInfo, error)
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Stop(context.Context, *Empty) (*Empty, error)
	GetStatus(context.Context, *Empty) (*StatusResponse, error)
	Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteResponse]) error
	Capabilities(context.Context, *Empty) (*CapabilityList, error)
	mustEmbedUnimplementedOrcaiPluginServer()
}

// UnimplementedOrcaiPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrcaiPluginServer struct{}

func (UnimplementedOrcaiPluginServer) GetInfo(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedOrcaiPluginServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedOrcaiPluginServer) Stop(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedOrcaiPluginServer) GetStatus(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedOrcaiPluginServer) Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteResponse]) error {
	return status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedOrcaiPluginServer) Capabilities(context.Context, *Empty) (*CapabilityList, error) {
	return nil, status.Error(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedOrcaiPluginServer) mustEmbedUnimplementedOrcaiPluginServer() {}
func (UnimplementedOrcaiPluginServer) testEmbeddedByValue()                     {}

// UnsafeOrcaiPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrcaiPluginServer will
// result in compilation errors.
type UnsafeOrcaiPluginServer interface {
	mustEmbedUnimplementedOrcaiPluginServer()
}

func RegisterOrcaiPluginServer(s grpc.ServiceRegistrar, srv OrcaiPluginServer) {
	// If the following call panics, it indicates UnimplementedOrcaiPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrcaiPlugin_ServiceDesc, srv)
}

func _OrcaiPlugin_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrcaiPluginServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrcaiPlugin_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrcaiPluginServer).GetInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrcaiPlugin_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrcaiPluginServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrcaiPlugin_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrcaiPluginServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrcaiPlugin_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrcaiPluginServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrcaiPlugin_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrcaiPluginServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrcaiPlugin_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrcaiPluginServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrcaiPlugin_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrcaiPluginServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrcaiPlugin_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrcaiPluginServer).Execute(m, &grpc.GenericServerStream[ExecuteRequest, ExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrcaiPlugin_ExecuteServer = grpc.ServerStreamingServer[ExecuteResponse]

func _OrcaiPlugin_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrcaiPluginServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrcaiPlugin_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrcaiPluginServer).Capabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// OrcaiPlugin_ServiceDesc is the grpc.ServiceDesc for OrcaiPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrcaiPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orcai.v1.OrcaiPlugin",
	HandlerType: (*OrcaiPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _OrcaiPlugin_GetInfo_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _OrcaiPlugin_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _OrcaiPlugin_Stop_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _OrcaiPlugin_GetStatus_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _OrcaiPlugin_Capabilities_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _OrcaiPlugin_Execute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
