// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: bridge.proto

package bridgepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{0}
}

type DescribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []*Capability          `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescribeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeResponse) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Inject        string                 `protobuf:"bytes,3,opt,name=inject,proto3" json:"inject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capability) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Capability) GetInject() string {
	if x != nil {
		return x.Inject
	}
	return ""
}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cwd           string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Input         string                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"` // mid-stream user reply to a WaitingPayload
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *SendRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *SendRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *SendRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *SendRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type WaitingPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hint          string                 `protobuf:"bytes,1,opt,name=hint,proto3" json:"hint,omitempty"` // partial prompt text from the subprocess, e.g. "[y/n] "
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitingPayload) Reset() {
	*x = WaitingPayload{}
	mi := &file_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitingPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitingPayload) ProtoMessage() {}

func (x *WaitingPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitingPayload.ProtoReflect.Descriptor instead.
func (*WaitingPayload) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *WaitingPayload) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type SendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SendResponse_Chunk
	//	*SendResponse_Done
	//	*SendResponse_Error
	//	*SendResponse_Waiting
	Payload       isSendResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *SendResponse) GetPayload() isSendResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendResponse) GetChunk() string {
	if x != nil {
		if x, ok := x.Payload.(*SendResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return ""
}

func (x *SendResponse) GetDone() *DonePayload {
	if x != nil {
		if x, ok := x.Payload.(*SendResponse_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *SendResponse) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*SendResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *SendResponse) GetWaiting() *WaitingPayload {
	if x != nil {
		if x, ok := x.Payload.(*SendResponse_Waiting); ok {
			return x.Waiting
		}
	}
	return nil
}

type isSendResponse_Payload interface {
	isSendResponse_Payload()
}

type SendResponse_Chunk struct {
	Chunk string `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type SendResponse_Done struct {
	Done *DonePayload `protobuf:"bytes,2,opt,name=done,proto3,oneof"`
}

type SendResponse_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type SendResponse_Waiting struct {
	Waiting *WaitingPayload `protobuf:"bytes,4,opt,name=waiting,proto3,oneof"`
}

func (*SendResponse_Chunk) isSendResponse_Payload() {}

func (*SendResponse_Done) isSendResponse_Payload() {}

func (*SendResponse_Error) isSendResponse_Payload() {}

func (*SendResponse_Waiting) isSendResponse_Payload() {}

type DonePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	InputTokens   int32                  `protobuf:"varint,3,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,4,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheTokens   int32                  `protobuf:"varint,5,opt,name=cache_tokens,json=cacheTokens,proto3" json:"cache_tokens,omitempty"`
	ContextWindow int32                  `protobuf:"varint,6,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DonePayload) Reset() {
	*x = DonePayload{}
	mi := &file_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DonePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonePayload) ProtoMessage() {}

func (x *DonePayload) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonePayload.ProtoReflect.Descriptor instead.
func (*DonePayload) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *DonePayload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DonePayload) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DonePayload) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *DonePayload) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *DonePayload) GetCacheTokens() int32 {
	if x != nil {
		return x.CacheTokens
	}
	return 0
}

func (x *DonePayload) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{7}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{8}
}

var File_bridge_proto protoreflect.FileDescriptor

const file_bridge_proto_rawDesc = "" +
	"\n" +
	"\fbridge.proto\x12\x06bridge\"\x11\n" +
	"\x0fDescribeRequest\"x\n" +
	"\x10DescribeResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x126\n" +
	"\fcapabilities\x18\x03 \x03(\v2\x12.bridge.CapabilityR\fcapabilities\"L\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06inject\x18\x03 \x01(\tR\x06inject\"\x82\x01\n" +
	"\vSendRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x12\x14\n" +
	"\x05input\x18\x04 \x01(\tR\x05input\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"$\n" +
	"\x0eWaitingPayload\x12\x12\n" +
	"\x04hint\x18\x01 \x01(\tR\x04hint\"\xa8\x01\n" +
	"\fSendResponse\x12\x16\n" +
	"\x05chunk\x18\x01 \x01(\tH\x00R\x05chunk\x12)\n" +
	"\x04done\x18\x02 \x01(\v2\x13.bridge.DonePayloadH\x00R\x04done\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x122\n" +
	"\awaiting\x18\x04 \x01(\v2\x16.bridge.WaitingPayloadH\x00R\awaitingB\t\n" +
	"\apayload\"\xd4\x01\n" +
	"\vDonePayload\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12!\n" +
	"\finput_tokens\x18\x03 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x04 \x01(\x05R\foutputTokens\x12!\n" +
	"\fcache_tokens\x18\x05 \x01(\x05R\vcacheTokens\x12%\n" +
	"\x0econtext_window\x18\x06 \x01(\x05R\rcontextWindow\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse2\xc5\x01\n" +
	"\x0eProviderBridge\x12=\n" +
	"\bDescribe\x12\x17.bridge.DescribeRequest\x1a\x18.bridge.DescribeResponse\x125\n" +
	"\x04Send\x12\x13.bridge.SendRequest\x1a\x14.bridge.SendResponse(\x010\x01\x12=\n" +
	"\bShutdown\x12\x17.bridge.ShutdownRequest\x1a\x18.bridge.ShutdownResponseB-Z+github.com/adam-stokes/orcai/proto/bridgepbb\x06proto3"

var (
	file_bridge_proto_rawDescOnce sync.Once
	file_bridge_proto_rawDescData []byte
)

func file_bridge_proto_rawDescGZIP() []byte {
	file_bridge_proto_rawDescOnce.Do(func() {
		file_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_proto_rawDesc), len(file_bridge_proto_rawDesc)))
	})
	return file_bridge_proto_rawDescData
}

var file_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bridge_proto_goTypes = []any{
	(*DescribeRequest)(nil),  // 0: bridge.DescribeRequest
	(*DescribeResponse)(nil), // 1: bridge.DescribeResponse
	(*Capability)(nil),       // 2: bridge.Capability
	(*SendRequest)(nil),      // 3: bridge.SendRequest
	(*WaitingPayload)(nil),   // 4: bridge.WaitingPayload
	(*SendResponse)(nil),     // 5: bridge.SendResponse
	(*DonePayload)(nil),      // 6: bridge.DonePayload
	(*ShutdownRequest)(nil),  // 7: bridge.ShutdownRequest
	(*ShutdownResponse)(nil), // 8: bridge.ShutdownResponse
}
var file_bridge_proto_depIdxs = []int32{
	2, // 0: bridge.DescribeResponse.capabilities:type_name -> bridge.Capability
	6, // 1: bridge.SendResponse.done:type_name -> bridge.DonePayload
	4, // 2: bridge.SendResponse.waiting:type_name -> bridge.WaitingPayload
	0, // 3: bridge.ProviderBridge.Describe:input_type -> bridge.DescribeRequest
	3, // 4: bridge.ProviderBridge.Send:input_type -> bridge.SendRequest
	7, // 5: bridge.ProviderBridge.Shutdown:input_type -> bridge.ShutdownRequest
	1, // 6: bridge.ProviderBridge.Describe:output_type -> bridge.DescribeResponse
	5, // 7: bridge.ProviderBridge.Send:output_type -> bridge.SendResponse
	8, // 8: bridge.ProviderBridge.Shutdown:output_type -> bridge.ShutdownResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bridge_proto_init() }
func file_bridge_proto_init() {
	if File_bridge_proto != nil {
		return
	}
	file_bridge_proto_msgTypes[5].OneofWrappers = []any{
		(*SendResponse_Chunk)(nil),
		(*SendResponse_Done)(nil),
		(*SendResponse_Error)(nil),
		(*SendResponse_Waiting)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_proto_rawDesc), len(file_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridge_proto_goTypes,
		DependencyIndexes: file_bridge_proto_depIdxs,
		MessageInfos:      file_bridge_proto_msgTypes,
	}.Build()
	File_bridge_proto = out.File
	file_bridge_proto_goTypes = nil
	file_bridge_proto_depIdxs = nil
}
