// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: bridge.proto

package bridgepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProviderBridge_Describe_FullMethodName = "/bridge.ProviderBridge/Describe"
	ProviderBridge_Send_FullMethodName     = "/bridge.ProviderBridge/Send"
	ProviderBridge_Shutdown_FullMethodName = "/bridge.ProviderBridge/Shutdown"
)

// ProviderBridgeClient is the client API for ProviderBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProviderBridgeClient interface {
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	Send(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendRequest, SendResponse], error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type providerBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderBridgeClient(cc grpc.ClientConnInterface) ProviderBridgeClient {
	return &providerBridgeClient{cc}
}

func (c *providerBridgeClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, ProviderBridge_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerBridgeClient) Send(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendRequest, SendResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProviderBridge_ServiceDesc.Streams[0], ProviderBridge_Send_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendRequest, SendResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderBridge_SendClient = grpc.BidiStreamingClient[SendRequest, SendResponse]

func (c *providerBridgeClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, ProviderBridge_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderBridgeServer is the server API for ProviderBridge service.
// All implementations must embed UnimplementedProviderBridgeServer
// for forward compatibility.
type ProviderBridgeServer interface {
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	Send(grpc.BidiStreamingServer[SendRequest, SendResponse]) error
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedProviderBridgeServer()
}

// UnimplementedProviderBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderBridgeServer struct{}

func (UnimplementedProviderBridgeServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedProviderBridgeServer) Send(grpc.BidiStreamingServer[SendRequest, SendResponse]) error {
	return status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedProviderBridgeServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedProviderBridgeServer) mustEmbedUnimplementedProviderBridgeServer() {}
func (UnimplementedProviderBridgeServer) testEmbeddedByValue()                        {}

// UnsafeProviderBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderBridgeServer will
// result in compilation errors.
type UnsafeProviderBridgeServer interface {
	mustEmbedUnimplementedProviderBridgeServer()
}

func RegisterProviderBridgeServer(s grpc.ServiceRegistrar, srv ProviderBridgeServer) {
	// If the following call panics, it indicates UnimplementedProviderBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProviderBridge_ServiceDesc, srv)
}

func _ProviderBridge_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderBridgeServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderBridge_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderBridgeServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderBridge_Send_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProviderBridgeServer).Send(&grpc.GenericServerStream[SendRequest, SendResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderBridge_SendServer = grpc.BidiStreamingServer[SendRequest, SendResponse]

func _ProviderBridge_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderBridgeServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderBridge_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderBridgeServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProviderBridge_ServiceDesc is the grpc.ServiceDesc for ProviderBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.ProviderBridge",
	HandlerType: (*ProviderBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _ProviderBridge_Describe_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _ProviderBridge_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Send",
			Handler:       _ProviderBridge_Send_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bridge.proto",
}
